version: '3.6'

services:
  admin:
    container_name: bizcard_admin
    build: ./docker
    restart: always
    volumes:
      - .:/var/www/bizcard
    ports:
      - "8014:80"
    depends_on:
      - db
    networks:
      - bizcard
    links: 
      - db

  db:
    container_name: bizcard_db
    image: mysql
    restart: always
    volumes:
      - /var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: bizcard
      MYSQL_USER: root
      MYSQL_PASSWORD: Asdfgh123456
      MYSQL_ROOT_PASSWORD: Asdfgh123456
    networks:
      - bizcard

networks:
  bizcard:
    driver: bridge