version: '3.6'

services:
  admin:
    container_name: bizcard
    build: ./
    ports:
      - "8014:80"
    restart: always
    volumes:
      - .:/var/www/bizcard
      
  mysql:
    image: mysql
    restart: always
    volumes:
      - /var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: bizcard
      MYSQL_USER: root
      MYSQL_PASSWORD: Asdfgh123456
      MYSQL_ROOT_PASSWORD: Asdfgh123456

  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions

networks:
  infra: